Added all features needed for programmer access
Saint-Francis-Robotics-Team2367/sumo-bots pull request #2
Opened 2024-07-27 23:54 UTC by zadelobo

Functions to read UDP packets, parse game state packages, parse controller state packages, and connect to Wi-Fi

2024-07-28 00:25 UTC, zeroDecoder requested changes

2024-07-28 00:25 UTC, zeroDecoder commented on robot-code/micro-python/client_udp_listen.py
> +ROBOT_NAME = "St. Francis"
These attributes should probably go in a class and be part of the constructor

2024-07-28 00:25 UTC, zeroDecoder commented on robot-code/micro-python/client_udp_listen.py
> +	for elem in [hex_list[i:i+16] for i in range(0, len(hex_list), 16)]:
double for loop nesting in one line is bad for readability and makes this comment hard. You included the first byte of the message in the range so all the names will be off by one.

2024-07-28 00:25 UTC, zeroDecoder commented on robot-code/micro-python/client_udp_listen.py
> +def connect_to_wifi():
This should get all this in a class

2024-07-28 23:28 UTC, zadelobo commented
@zeroDecoder pushed the changes requested to the python-client branch. Requesting another code review.

2024-08-03 22:50 UTC, zeroDecoder approved these changes
LGTM

2024-08-03 22:50 UTC, merged